name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        submodules: true
      - name: Build Docker
        run: docker build . -t paged_archive
      - name: Run Tests
        run: docker run -t paged_archive
